### ISSUE TITLE
Karma 'smite' link not showing on forum

### ISSUE THREAD

**Issue by Reload86** [iamdansker/Far-Shiverpeaks-Development#36]
The 'smite' link doesn't show on the forum, it does show in pm's though. This is an urgent matter... I need to get smiting zeph, he's on a lofty 3 karma already! :)

**Comment by vennekilde** [comment]
Lol, smite should be there though, however someone renamed them to Huzzah! and Why I aughta..

I have considered changing it as it isn't very intuitive (i pressed the links multiple times without realizing what it did)

If you can't see those 2 links, then please reply back

**Comment by Reload86** [comment]
Yeah I might of changed those ;) that's what I mean though, only huzzah! actually shows up, the why I aughta.. is missing, but it does show on the pm threads

**Comment by vennekilde** [comment]
It is because of the inferno theme

We discussed a some point if we should allow downvoting due to potential abuse, however we never really came to a conclusion
However i removed the html code for it on the inferno theme (forgot about it)

I will ask the others how they feel about downvoting before i either add or remove it

**Comment by vennekilde** [comment]
Alright, i'll add the option back to the inferno theme, however we really need to rename the buttons XD
